/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/': {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  '/bonuses': {
    get: {
      parameters: {
        query: {
          id?: parameters['rowFilter.bonuses.id'];
          created_at?: parameters['rowFilter.bonuses.created_at'];
          amount?: parameters['rowFilter.bonuses.amount'];
          reason?: parameters['rowFilter.bonuses.reason'];
          employee_id?: parameters['rowFilter.bonuses.employee_id'];
          /** Filtering Columns */
          select?: parameters['select'];
          /** Ordering */
          order?: parameters['order'];
          /** Limiting and Pagination */
          offset?: parameters['offset'];
          /** Limiting and Pagination */
          limit?: parameters['limit'];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters['range'];
          /** Limiting and Pagination */
          'Range-Unit'?: parameters['rangeUnit'];
          /** Preference */
          Prefer?: parameters['preferCount'];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions['bonuses'][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** bonuses */
          bonuses?: definitions['bonuses'];
        };
        query: {
          /** Filtering Columns */
          select?: parameters['select'];
        };
        header: {
          /** Preference */
          Prefer?: parameters['preferReturn'];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters['rowFilter.bonuses.id'];
          created_at?: parameters['rowFilter.bonuses.created_at'];
          amount?: parameters['rowFilter.bonuses.amount'];
          reason?: parameters['rowFilter.bonuses.reason'];
          employee_id?: parameters['rowFilter.bonuses.employee_id'];
        };
        header: {
          /** Preference */
          Prefer?: parameters['preferReturn'];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters['rowFilter.bonuses.id'];
          created_at?: parameters['rowFilter.bonuses.created_at'];
          amount?: parameters['rowFilter.bonuses.amount'];
          reason?: parameters['rowFilter.bonuses.reason'];
          employee_id?: parameters['rowFilter.bonuses.employee_id'];
        };
        body: {
          /** bonuses */
          bonuses?: definitions['bonuses'];
        };
        header: {
          /** Preference */
          Prefer?: parameters['preferReturn'];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  '/employee_roles': {
    get: {
      parameters: {
        query: {
          id?: parameters['rowFilter.employee_roles.id'];
          created_at?: parameters['rowFilter.employee_roles.created_at'];
          name?: parameters['rowFilter.employee_roles.name'];
          /** Filtering Columns */
          select?: parameters['select'];
          /** Ordering */
          order?: parameters['order'];
          /** Limiting and Pagination */
          offset?: parameters['offset'];
          /** Limiting and Pagination */
          limit?: parameters['limit'];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters['range'];
          /** Limiting and Pagination */
          'Range-Unit'?: parameters['rangeUnit'];
          /** Preference */
          Prefer?: parameters['preferCount'];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions['employee_roles'][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** employee_roles */
          employee_roles?: definitions['employee_roles'];
        };
        query: {
          /** Filtering Columns */
          select?: parameters['select'];
        };
        header: {
          /** Preference */
          Prefer?: parameters['preferReturn'];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters['rowFilter.employee_roles.id'];
          created_at?: parameters['rowFilter.employee_roles.created_at'];
          name?: parameters['rowFilter.employee_roles.name'];
        };
        header: {
          /** Preference */
          Prefer?: parameters['preferReturn'];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters['rowFilter.employee_roles.id'];
          created_at?: parameters['rowFilter.employee_roles.created_at'];
          name?: parameters['rowFilter.employee_roles.name'];
        };
        body: {
          /** employee_roles */
          employee_roles?: definitions['employee_roles'];
        };
        header: {
          /** Preference */
          Prefer?: parameters['preferReturn'];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  '/employees': {
    get: {
      parameters: {
        query: {
          id?: parameters['rowFilter.employees.id'];
          created_at?: parameters['rowFilter.employees.created_at'];
          first_name?: parameters['rowFilter.employees.first_name'];
          last_name?: parameters['rowFilter.employees.last_name'];
          birth_date?: parameters['rowFilter.employees.birth_date'];
          salary?: parameters['rowFilter.employees.salary'];
          income_percentage?: parameters['rowFilter.employees.income_percentage'];
          role_id?: parameters['rowFilter.employees.role_id'];
          /** Filtering Columns */
          select?: parameters['select'];
          /** Ordering */
          order?: parameters['order'];
          /** Limiting and Pagination */
          offset?: parameters['offset'];
          /** Limiting and Pagination */
          limit?: parameters['limit'];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters['range'];
          /** Limiting and Pagination */
          'Range-Unit'?: parameters['rangeUnit'];
          /** Preference */
          Prefer?: parameters['preferCount'];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions['employees'][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** employees */
          employees?: definitions['employees'];
        };
        query: {
          /** Filtering Columns */
          select?: parameters['select'];
        };
        header: {
          /** Preference */
          Prefer?: parameters['preferReturn'];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters['rowFilter.employees.id'];
          created_at?: parameters['rowFilter.employees.created_at'];
          first_name?: parameters['rowFilter.employees.first_name'];
          last_name?: parameters['rowFilter.employees.last_name'];
          birth_date?: parameters['rowFilter.employees.birth_date'];
          salary?: parameters['rowFilter.employees.salary'];
          income_percentage?: parameters['rowFilter.employees.income_percentage'];
          role_id?: parameters['rowFilter.employees.role_id'];
        };
        header: {
          /** Preference */
          Prefer?: parameters['preferReturn'];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters['rowFilter.employees.id'];
          created_at?: parameters['rowFilter.employees.created_at'];
          first_name?: parameters['rowFilter.employees.first_name'];
          last_name?: parameters['rowFilter.employees.last_name'];
          birth_date?: parameters['rowFilter.employees.birth_date'];
          salary?: parameters['rowFilter.employees.salary'];
          income_percentage?: parameters['rowFilter.employees.income_percentage'];
          role_id?: parameters['rowFilter.employees.role_id'];
        };
        body: {
          /** employees */
          employees?: definitions['employees'];
        };
        header: {
          /** Preference */
          Prefer?: parameters['preferReturn'];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  '/prepaid_expenses': {
    get: {
      parameters: {
        query: {
          id?: parameters['rowFilter.prepaid_expenses.id'];
          created_at?: parameters['rowFilter.prepaid_expenses.created_at'];
          amount?: parameters['rowFilter.prepaid_expenses.amount'];
          employee_id?: parameters['rowFilter.prepaid_expenses.employee_id'];
          /** Filtering Columns */
          select?: parameters['select'];
          /** Ordering */
          order?: parameters['order'];
          /** Limiting and Pagination */
          offset?: parameters['offset'];
          /** Limiting and Pagination */
          limit?: parameters['limit'];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters['range'];
          /** Limiting and Pagination */
          'Range-Unit'?: parameters['rangeUnit'];
          /** Preference */
          Prefer?: parameters['preferCount'];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions['prepaid_expenses'][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** prepaid_expenses */
          prepaid_expenses?: definitions['prepaid_expenses'];
        };
        query: {
          /** Filtering Columns */
          select?: parameters['select'];
        };
        header: {
          /** Preference */
          Prefer?: parameters['preferReturn'];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters['rowFilter.prepaid_expenses.id'];
          created_at?: parameters['rowFilter.prepaid_expenses.created_at'];
          amount?: parameters['rowFilter.prepaid_expenses.amount'];
          employee_id?: parameters['rowFilter.prepaid_expenses.employee_id'];
        };
        header: {
          /** Preference */
          Prefer?: parameters['preferReturn'];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters['rowFilter.prepaid_expenses.id'];
          created_at?: parameters['rowFilter.prepaid_expenses.created_at'];
          amount?: parameters['rowFilter.prepaid_expenses.amount'];
          employee_id?: parameters['rowFilter.prepaid_expenses.employee_id'];
        };
        body: {
          /** prepaid_expenses */
          prepaid_expenses?: definitions['prepaid_expenses'];
        };
        header: {
          /** Preference */
          Prefer?: parameters['preferReturn'];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  '/retentions': {
    get: {
      parameters: {
        query: {
          id?: parameters['rowFilter.retentions.id'];
          created_at?: parameters['rowFilter.retentions.created_at'];
          amount?: parameters['rowFilter.retentions.amount'];
          employee_id?: parameters['rowFilter.retentions.employee_id'];
          /** Filtering Columns */
          select?: parameters['select'];
          /** Ordering */
          order?: parameters['order'];
          /** Limiting and Pagination */
          offset?: parameters['offset'];
          /** Limiting and Pagination */
          limit?: parameters['limit'];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters['range'];
          /** Limiting and Pagination */
          'Range-Unit'?: parameters['rangeUnit'];
          /** Preference */
          Prefer?: parameters['preferCount'];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions['retentions'][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** retentions */
          retentions?: definitions['retentions'];
        };
        query: {
          /** Filtering Columns */
          select?: parameters['select'];
        };
        header: {
          /** Preference */
          Prefer?: parameters['preferReturn'];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters['rowFilter.retentions.id'];
          created_at?: parameters['rowFilter.retentions.created_at'];
          amount?: parameters['rowFilter.retentions.amount'];
          employee_id?: parameters['rowFilter.retentions.employee_id'];
        };
        header: {
          /** Preference */
          Prefer?: parameters['preferReturn'];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters['rowFilter.retentions.id'];
          created_at?: parameters['rowFilter.retentions.created_at'];
          amount?: parameters['rowFilter.retentions.amount'];
          employee_id?: parameters['rowFilter.retentions.employee_id'];
        };
        body: {
          /** retentions */
          retentions?: definitions['retentions'];
        };
        header: {
          /** Preference */
          Prefer?: parameters['preferReturn'];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  '/shifts': {
    get: {
      parameters: {
        query: {
          id?: parameters['rowFilter.shifts.id'];
          employee_id?: parameters['rowFilter.shifts.employee_id'];
          date?: parameters['rowFilter.shifts.date'];
          duration?: parameters['rowFilter.shifts.duration'];
          created_at?: parameters['rowFilter.shifts.created_at'];
          /** Filtering Columns */
          select?: parameters['select'];
          /** Ordering */
          order?: parameters['order'];
          /** Limiting and Pagination */
          offset?: parameters['offset'];
          /** Limiting and Pagination */
          limit?: parameters['limit'];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters['range'];
          /** Limiting and Pagination */
          'Range-Unit'?: parameters['rangeUnit'];
          /** Preference */
          Prefer?: parameters['preferCount'];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions['shifts'][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** shifts */
          shifts?: definitions['shifts'];
        };
        query: {
          /** Filtering Columns */
          select?: parameters['select'];
        };
        header: {
          /** Preference */
          Prefer?: parameters['preferReturn'];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters['rowFilter.shifts.id'];
          employee_id?: parameters['rowFilter.shifts.employee_id'];
          date?: parameters['rowFilter.shifts.date'];
          duration?: parameters['rowFilter.shifts.duration'];
          created_at?: parameters['rowFilter.shifts.created_at'];
        };
        header: {
          /** Preference */
          Prefer?: parameters['preferReturn'];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters['rowFilter.shifts.id'];
          employee_id?: parameters['rowFilter.shifts.employee_id'];
          date?: parameters['rowFilter.shifts.date'];
          duration?: parameters['rowFilter.shifts.duration'];
          created_at?: parameters['rowFilter.shifts.created_at'];
        };
        body: {
          /** shifts */
          shifts?: definitions['shifts'];
        };
        header: {
          /** Preference */
          Prefer?: parameters['preferReturn'];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  bonuses: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: bigint */
    amount: number;
    /** Format: text */
    reason?: string;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `employees.id`.<fk table='employees' column='id'/>
     */
    employee_id: number;
  };
  employee_roles: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: text */
    name: string;
  };
  employees: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: text */
    first_name: string;
    /** Format: text */
    last_name?: string;
    /** Format: date */
    birth_date?: string;
    /** Format: bigint */
    salary: number;
    /** Format: numeric */
    income_percentage: number;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `employee_roles.id`.<fk table='employee_roles' column='id'/>
     */
    role_id: number;
  };
  /** @description The work shifts for each employee */
  shifts: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `employees.id`.<fk table='employees' column='id'/>
     */
    employee_id: number;
    /** Format: timestamp without time zone */
    date: string;
    /** Format: smallint */
    duration: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: 'params=single-object';
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: 'return=representation' | 'return=minimal' | 'return=none';
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: 'count=none';
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description bonuses */
  'body.bonuses': definitions['bonuses'];
  /** Format: bigint */
  'rowFilter.bonuses.id': string;
  /** Format: timestamp with time zone */
  'rowFilter.bonuses.created_at': string;
  /** Format: bigint */
  'rowFilter.bonuses.amount': string;
  /** Format: text */
  'rowFilter.bonuses.reason': string;
  /** Format: bigint */
  'rowFilter.bonuses.employee_id': string;
  /** @description employee_roles */
  'body.employee_roles': definitions['employee_roles'];
  /** Format: bigint */
  'rowFilter.employee_roles.id': string;
  /** Format: timestamp with time zone */
  'rowFilter.employee_roles.created_at': string;
  /** Format: text */
  'rowFilter.employee_roles.name': string;
  /** @description employees */
  'body.employees': definitions['employees'];
  /** Format: bigint */
  'rowFilter.employees.id': string;
  /** Format: timestamp with time zone */
  'rowFilter.employees.created_at': string;
  /** Format: text */
  'rowFilter.employees.first_name': string;
  /** Format: text */
  'rowFilter.employees.last_name': string;
  /** Format: date */
  'rowFilter.employees.birth_date': string;
  /** Format: bigint */
  'rowFilter.employees.salary': string;
  /** Format: numeric */
  'rowFilter.employees.income_percentage': string;
  /** Format: bigint */
  'rowFilter.employees.role_id': string;
  /** @description shifts */
  'body.shifts': definitions['shifts'];
  /** Format: bigint */
  'rowFilter.shifts.id': string;
  /** Format: bigint */
  'rowFilter.shifts.employee_id': string;
  /** Format: timestamp without time zone */
  'rowFilter.shifts.date': string;
  /** Format: smallint */
  'rowFilter.shifts.duration': string;
  /** Format: timestamp with time zone */
  'rowFilter.shifts.created_at': string;
}

export interface operations {}

export interface external {}
